Add non supported bugfix and security patch until dates
ember-learn/ember-website pull request #1083
Opened 2024-02-11 20:18 UTC by geneukum

Per [this message](https://discord.com/channels/480462759797063690/1131610462207873025/1164957530112409670) in the ember-js discord, let's add a couple of new columns (Bugfixes until and Security patches until) to the no longer maintained LTS table on the `releases/lts` route.

While glossing over this, I _think_ that I caught a few instances where we were showing the incorrect minor version / date for a few LTS versions as well, but definitely worth double checking them.

2024-02-12 17:49 UTC, kategengler commented on app/templates/releases/lts.hbs
> +    {{#each this.noLongerMaintainedLTS as |release|}}
Thank you so much for tackling this!

I think it may be better to keep this as a static table, since the values, once added, do not change.

2024-02-12 21:18 UTC, kategengler submitted a review, later dismissed

2024-02-12 22:20 UTC, kategengler requested changes
Change the column from the last minor date to the LTS promotion date based on the blog post dates

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>January 2019</td>
```suggestion
      <td>October 15, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>February 2018</td>
```suggestion
      <td>February 14, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>February 2018</td>
```suggestion
      <td>November 20, 2017</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>April 2017</td>
```suggestion
      <td>April 29, 2017</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>November 2016</td>
```suggestion
      <td>October 17, 2016</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>April 2016</td>
```suggestion
      <td>April 11, 2016</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>August 2023</td>
```suggestion
      <td>July 6, 2023</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>December 2023</td>
```suggestion
      <td>December 21, 2023</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>March 2023</td>
```suggestion
      <td>February 8, 2023</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>July 2023</td>
```suggestion
      <td>July 26, 2023</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>August 2022</td>
```suggestion
      <td>July 18, 2022</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>January 2023</td>
```suggestion
      <td>January 2, 2023</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
>        <td>November 2021</td>
```suggestion
      <td>September 23, 2021</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>March 2022</td>
```suggestion
      <td>March 10, 2022</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>May 2021</td>
```suggestion
      <td>March 31, 2021</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>September 2021</td>
```suggestion
      <td>September 15, 2021</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>November 2020</td>
```suggestion
      <td>October 12, 2020</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>March 2021</td>
```suggestion
      <td>March 29, 2021</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>June 2020</td>
```suggestion
      <td>April 22, 2020</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>October 2020</td>
```suggestion
      <td>October 7, 2020</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>December 2019</td>
```suggestion
      <td>November 6, 2019</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>April 2020</td>
```suggestion
      <td>April 22, 2020</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>June 2019</td>
```suggestion
      <td>May 13, 2019</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>October 2019</td>
```suggestion
      <td>October 28, 2019</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>October 2018</td>
```suggestion
      <td>September 12, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>February 2019</td>
```suggestion
      <td>February 27, 2019</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>July 2018</td>
```suggestion
      <td>June 18, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>December 2018</td>
```suggestion
      <td>December 3, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>January 2018</td>
```suggestion
      <td>November 25, 2017</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>May 2018</td>
```suggestion
      <td>May 12, 2018</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>June 2017</td>
```suggestion
      <td>May 15, 2017</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>October 2017</td>
```suggestion
      <td>October 30, 2017</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>December 2016</td>
```suggestion
      <td>November 7, 2016</td>
```

2024-02-12 22:20 UTC, kategengler commented on app/templates/releases/lts.hbs
> +      <td>April 2017</td>
```suggestion
      <td>April 24, 2017</td>
```

2024-02-12 22:22 UTC, kategengler approved these changes

2024-02-12 22:23 UTC, kategengler commented
Thank you for this; if you're up for another PR after this, I think removing that latest minor version column could be useful. It seems like something that is irksome to keep up to date. We could link to the npm versions page instead https://www.npmjs.com/package/ember-source?activeTab=versions

2024-02-13 00:24 UTC, geneukum commented
> Thank you for this; if you're up for another PR after this, I think removing that latest minor version column could be useful. It seems like something that is irksome to keep up to date. We could link to the npm versions page instead https://www.npmjs.com/package/ember-source?activeTab=versions

Sure thing! Good idea to switch the last minor date to the promotion date. I think that it was a little funky because some LTS versions received patches after the cutoffs if I remember correctly. 

I'll make a separate PR to drop that column and add some text to link to the versions page on NPM instead.

2024-02-13 17:09 UTC, kategengler commented
@ember-learn/learning-core-team who can review Percy?

2024-02-14 15:01 UTC, merged