Adding Krystan HuffMenne to the Ember Data core team
ember-learn/ember-website pull request #1105
Opened 2024-04-30 05:52 UTC by kiwiupover

This PR adds Krystan HuffMenne to the Ember Data core team
and moves Scott Newcomber to alumni

2024-04-30 05:56 UTC, wagenet approved these changes

2024-04-30 20:40 UTC, runspired approved these changes

2024-04-30 20:43 UTC, IgnaceMaes approved these changes
Thanks Scott for your contributions 🙌 

And congrats Krystan 👏

2024-04-30 20:45 UTC, IgnaceMaes requested changes
Looks like two tests are failing. If you could make a quick adjustment to the assertions that would be great. Otherwise I can get back to it when I'm on a computer.

2024-04-30 22:22 UTC, gitKrystan commented on tests/unit/controllers/teams-test.js
> +    assert.deepEqual(output, ['chris-thoburn', 'krystan-huffMenne']);
```suggestion
    assert.deepEqual(output, ['chris-thoburn', 'krystan-huffmenne']);
```

2024-05-01 06:14 UTC, IgnaceMaes approved these changes

2024-05-01 06:14 UTC, IgnaceMaes commented
Thanks!

2024-05-01 06:14 UTC, merged