Upgrade ember-page-title
ember-learn/ember-website pull request #716
Opened 2021-01-12 16:54 UTC by czikarito

Resolves https://github.com/ember-learn/ember-website/issues

### Notes
According to https://github.com/ember-cli/ember-page-title#upgrading-notes-for-5x-to-6x I had to remove usage of `HeadLayout` from `application.hbs`

2021-01-12 17:42 UTC, ijlee2 commented on app/templates/application.hbs
> -<HeadLayout />
It looks like deleting `<HeadLayout>` resulted in a breaking change for us. Previously, we could see 3 `<meta>` tags in the deploy preview website:

<img width="640" alt="Screen Shot 2021-01-12 at 6 38 59 PM" src="https://user-images.githubusercontent.com/16869656/104351358-93ee5680-5505-11eb-8eb7-2bee0fb40c25.png">

Now that `ember-page-title` no longer depends on `ember-cli-head`, I think we'll need to find another way to dynamically create these meta tags.

References:

- https://github.com/ember-cli/ember-page-title/issues/201
- https://github.com/emberjs/rfcs/pull/645#issuecomment-698391919

2021-01-12 17:45 UTC, ijlee2 requested changes
@czikarito Thanks for investigating and working on making the pull request.

I think we'll need to find a solution for continuing to create the 3 meta tags. Let me block merging this pull request until we can do so.

2021-01-12 17:52 UTC, ijlee2 commented on app/templates/application.hbs
> -<HeadLayout />
I asked for help on Discord: https://discord.com/channels/480462759797063690/480501885837770763/798610097319444520

2021-01-12 20:14 UTC, czikarito commented
@ijlee2 good catch. Maybe we can change only `{{title}}` to `{{page-title}}` in this PR (skip `ember-page-title` upgrade) to remove warnings in the console? and do the upgrade in the separate PR (when we'll find a solution)

2021-01-12 21:08 UTC, ijlee2 commented
> @ijlee2 good catch. Maybe we can change only `{{title}}` to `{{page-title}}` in this PR (skip `ember-page-title` upgrade) to remove warnings in the console? and do the upgrade in the separate PR (when we'll find a solution)

Yep, I think it'll be okay to just update the helpers. Thanks for the suggestion!

2021-01-12 21:13 UTC, czikarito commented
@ijlee2 I updated PR to include only helpers change

2021-01-12 21:21 UTC, ijlee2 approved these changes
CI logs look great, thank you again! ✨

2021-01-12 21:21 UTC, merged

2021-01-15 16:11 UTC, bertdeblock commented
👋 @ijlee2, the [titleDidUpdate hook PR](https://github.com/ember-cli/ember-page-title/pull/207) has been released, so I think that clears the path for updating `ember-page-title` inside this project.

2021-01-15 17:48 UTC, raido commented
Example integration with ember-cli-head - https://github.com/ember-cli/ember-page-title/issues/201#issuecomment-761081734

2021-01-15 19:15 UTC, ijlee2 commented
@bertdeblock @raido Thank you for working on a solution quickly! I'd be happy to try it out right away.