Add Ember Fest videos to videos links
ember-learn/ember-website pull request #986
Opened 2022-12-29 12:46 UTC by tniezurawski

Adds a link to Ember Fest videos: https://www.youtube.com/@emberfest/videos

# 😇 After

![image](https://user-images.githubusercontent.com/4335166/209953019-420aefd0-ad35-4578-9fb4-ab062d80c5f1.png)

2023-01-02 15:19 UTC, MinThaMie requested changes
Thanks for adding this. On the website EmberFest is written together :)

2023-01-02 15:19 UTC, MinThaMie commented on app/templates/index.hbs
> +          <li><a href="https://www.youtube.com/@emberfest/videos">Ember Fest Videos</a></li>
```suggestion
          <li><a href="https://www.youtube.com/@emberfest/videos">EmberFest Videos</a></li>
```

2023-01-03 10:12 UTC, tniezurawski commented
@MinThaMie Good spot :+1: I changed that.

I was following the YT channel. I guess they are not consistent with the name 😅

![image](https://user-images.githubusercontent.com/4335166/210337342-60082500-e008-48e5-bec0-685f429c6757.png)

2023-01-04 09:10 UTC, MinThaMie approved these changes

2023-01-04 09:10 UTC, merged